name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore src/DynamoDBProcessor/DynamoDBProcessor.csproj

    - name: Build
      run: dotnet build src/DynamoDBProcessor/DynamoDBProcessor.csproj --no-restore

    - name: Test with coverage
      run: |
        dotnet test src/DynamoDBProcessor/DynamoDBProcessor.csproj \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage \
          --logger:"console;verbosity=detailed" \
          --logger:"trx;LogFileName=test-results.trx"

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:"./coverage/**/coverage.cobertura.xml" \
          -targetdir:"./coverage/report" \
          -reporttypes:"Html;Badges;MarkdownSummary"

    - name: Extract coverage metrics
      id: coverage
      run: |
        COVERAGE=$(grep -oP '(?<=<coverage line-rate=")[^"]*' ./coverage/**/coverage.cobertura.xml)
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE"

    - name: Extract test results
      id: test-results
      run: |
        TOTAL=$(grep -oP '(?<=total=")[^"]*' ./coverage/**/coverage.cobertura.xml)
        PASSED=$(grep -oP '(?<=passed=")[^"]*' ./coverage/**/coverage.cobertura.xml)
        SUCCESS_RATE=$(echo "scale=2; ($PASSED/$TOTAL)*100" | bc)
        echo "success_rate=$SUCCESS_RATE" >> $GITHUB_OUTPUT
        echo "Success Rate: $SUCCESS_RATE%"

    - name: Update README with coverage
      run: |
        # Read the current README
        README_CONTENT=$(cat README.md)
        
        # Check if the badges section exists
        if [[ $README_CONTENT == *"## Test Coverage"* ]]; then
          # Update existing badges
          sed -i "s/!\[Test Coverage\].*/![Test Coverage](https://img.shields.io/badge/Test%20Coverage-${COVERAGE}%25-brightgreen)/" README.md
          sed -i "s/!\[Test Success Rate\].*/![Test Success Rate](https://img.shields.io/badge/Test%20Success%20Rate-${SUCCESS_RATE}%25-brightgreen)/" README.md
        else
          # Add new badges section
          echo -e "\n## Test Coverage\n" >> README.md
          echo "![Test Coverage](https://img.shields.io/badge/Test%20Coverage-${COVERAGE}%25-brightgreen)" >> README.md
          echo "![Test Success Rate](https://img.shields.io/badge/Test%20Success%20Rate-${SUCCESS_RATE}%25-brightgreen)" >> README.md
        fi

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update test coverage statistics [skip ci]" && git push)

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./coverage/report

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./coverage/**/test-results.trx 